// Code generated
// This file is a generated precompile contract config with stubbed abstract functions.
// The file is generated by a template. Please inspect every code and comment in this file before use.

package ieddsa

import (
	"errors"
	"fmt"
	"math/big"

	"github.com/ava-labs/subnet-evm/accounts/abi"
	"github.com/ava-labs/subnet-evm/precompile/contract"
	"github.com/ava-labs/subnet-evm/vmerrs"

	_ "embed"

	"github.com/ethereum/go-ethereum/common"
)

const (
	// Gas costs for each function. These are set to 1 by default.
	// You should set a gas cost for each function in your contract.
	// Generally, you should not set gas costs very low as this may cause your network to be vulnerable to DoS attacks.
	// There are some predefined gas costs in contract/utils.go that you can use.
	VerifyGasCost uint64 = 1 /* SET A GAS COST HERE */
)

// CUSTOM CODE STARTS HERE
// Reference imports to suppress errors from unused imports. This code and any unnecessary imports can be removed.
var (
	_ = abi.JSON
	_ = errors.New
	_ = big.NewInt
	_ = vmerrs.ErrOutOfGas
	_ = common.Big0
)

// Singleton StatefulPrecompiledContract and signatures.
var (

	// IEdDSARawABI contains the raw ABI of IEdDSA contract.
	//go:embed contract.abi
	IEdDSARawABI string

	IEdDSAABI = contract.ParseABI(IEdDSARawABI)

	IEdDSAPrecompile = createIEdDSAPrecompile()
)

// IEdDSAG1Point is an auto generated low-level Go binding around an user-defined struct.
type IEdDSAG1Point struct {
	X *big.Int
	Y *big.Int
}

// IEdDSAG2Point is an auto generated low-level Go binding around an user-defined struct.
type IEdDSAG2Point struct {
	X *big.Int
	Y *big.Int
}

// IEdDSAPublicKey is an auto generated low-level Go binding around an user-defined struct.
type IEdDSAPublicKey struct {
	A IEdDSAG2Point
}

// IEdDSASignature is an auto generated low-level Go binding around an user-defined struct.
type IEdDSASignature struct {
	R IEdDSAG1Point
	S *big.Int
}

type VerifyInput struct {
	PublicKey IEdDSAPublicKey
	Message   *big.Int
	Signature IEdDSASignature
}

// UnpackVerifyInput attempts to unpack [input] as VerifyInput
// assumes that [input] does not include selector (omits first 4 func signature bytes)
func UnpackVerifyInput(input []byte) (VerifyInput, error) {
	inputStruct := VerifyInput{}
	err := IEdDSAABI.UnpackInputIntoInterface(&inputStruct, "verify", input)

	return inputStruct, err
}

// PackVerify packs [inputStruct] of type VerifyInput into the appropriate arguments for verify.
func PackVerify(inputStruct VerifyInput) ([]byte, error) {
	return IEdDSAABI.Pack("verify", inputStruct.PublicKey, inputStruct.Message, inputStruct.Signature)
}

// PackVerifyOutput attempts to pack given result of type bool
// to conform the ABI outputs.
func PackVerifyOutput(result bool) ([]byte, error) {
	return IEdDSAABI.PackOutput("verify", result)
}

// UnpackVerifyOutput attempts to unpack given [output] into the bool type output
// assumes that [output] does not include selector (omits first 4 func signature bytes)
func UnpackVerifyOutput(output []byte) (bool, error) {
	res, err := IEdDSAABI.Unpack("verify", output)
	if err != nil {
		return false, err
	}
	unpacked := *abi.ConvertType(res[0], new(bool)).(*bool)
	return unpacked, nil
}

func verify(accessibleState contract.AccessibleState, caller common.Address, addr common.Address, input []byte, suppliedGas uint64, readOnly bool) (ret []byte, remainingGas uint64, err error) {
	if remainingGas, err = contract.DeductGas(suppliedGas, VerifyGasCost); err != nil {
		return nil, 0, err
	}
	// attempts to unpack [input] into the arguments to the VerifyInput.
	// Assumes that [input] does not include selector
	// You can use unpacked [inputStruct] variable in your code
	inputStruct, err := UnpackVerifyInput(input)
	if err != nil {
		return nil, remainingGas, err
	}

	// CUSTOM CODE STARTS HERE
	_ = inputStruct // CUSTOM CODE OPERATES ON INPUT

	var output bool // CUSTOM CODE FOR AN OUTPUT
	packedOutput, err := PackVerifyOutput(output)
	if err != nil {
		return nil, remainingGas, err
	}

	// Return the packed output and the remaining gas
	return packedOutput, remainingGas, nil
}

// createIEdDSAPrecompile returns a StatefulPrecompiledContract with getters and setters for the precompile.

func createIEdDSAPrecompile() contract.StatefulPrecompiledContract {
	var functions []*contract.StatefulPrecompileFunction

	abiFunctionMap := map[string]contract.RunStatefulPrecompileFunc{
		"verify": verify,
	}

	for name, function := range abiFunctionMap {
		method, ok := IEdDSAABI.Methods[name]
		if !ok {
			panic(fmt.Errorf("given method (%s) does not exist in the ABI", name))
		}
		functions = append(functions, contract.NewStatefulPrecompileFunction(method.ID, function))
	}
	// Construct the contract with no fallback function.
	statefulContract, err := contract.NewStatefulPrecompileContract(nil, functions)
	if err != nil {
		panic(err)
	}
	return statefulContract
}
